version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8080:8080
    environment:
      DEVELOPMENT: "true"
      NODOS_HOST: "0.0.0.0"
    command: "npm start"
