version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 8080:8080
    environment:
      DEVELOPMENT: "true"
      NODOS_HOST: "0.0.0.0"
    command: "npm start"

  caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile\
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
